version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    command:
      - echo installing packages `date`
      - npm install
      - echo building `date`
      - npm start

artifacts:
  files:
    - '**/*'